### ISSUE TITLE
Images are darkened when browsing through subreddits

### ISSUE THREAD

**Issue by Tiagoquix** [nopperl/load-reddit-images-directly#11]
It seems like since the introduction of #9 and having the option enabled some images will be darkened after scrolling through the subreddit for a while. This behavior is inconsistent. I think it has something to do with the lightbox, since the lightbox also exists when not in a post and instead in a general view such as https://www.reddit.com/r/memes/top/?t=all.

**Comment by nopperl** [comment]
Good idea, this should have been restricted to it from the start.
