### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by brndd** [nopperl/load-reddit-images-directly#16]
Since seemingly a few days ago, the extension no longer works. Not sure what changed, as I'm not familiar with how Reddit *used* to behave. Visiting a direct image link (e.g. https://i.redd.it/vcfftomz9ttc1.jpeg) now has the server return 307 Temporary Redirect to a page that embeds the image, and this is not blocked by the addon.

**Comment by mlynch** [comment]
Sadge, this extension is making new reddit actually bearable for me

**Comment by nopperl** [comment]
@brndd @mlynch that's curious, could you send me the URL that https://i.redd.it/vcfftomz9ttc1.jpeg redirects to on your end?

I can't reproduce this. I just tried it again on a new Firefox installation on both new and old reddit and it still works (including your provided link).

**Comment by brndd** [comment]
It redirected me to https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fvcfftomz9ttc1.jpeg

However, the addon now seems to spontaneously work again with no changes on my end -- I don't think I even updated Firefox in the mean time. I'll let you know if the issue comes back.

**Comment by Tiagoquix** [comment]
Hi, is this still relevant? It works normally for me on Firefox.

**Comment by brndd** [comment]
No. Everything looks to work fine now.
