### ISSUE TITLE
Feature request: always prioritize i.redd.it

### ISSUE THREAD

**Issue by Tiagoquix** [nopperl/load-reddit-images-directly#18]
Hi there.

Even with the option `Redirect preview images to the original image URL (i.redd.it) if possible` enabled, sometimes Reddit opens the image in the "preview.redd.it" link instead of "i.redd.it". Reloading the page makes it redirect to "i.redd.it" normally. I would like to request a feature so when it detects it's in a "preview.redd.it" page it automatically forces a reload, therefore correctly going to "i.redd.it".

Thanks for your attention.

**Comment by nopperl** [comment]
Hi @Tiagoquix!

>Even with the option Redirect preview images to the original image URL (i.redd.it) if possible enabled, sometimes Reddit opens the image in the "preview.redd.it" link instead of "i.redd.it".

Could you send me an example URL where this happens? I have not encountered this behavior yet. I assume it is similar to #14?

>Also, not sure if this is related, but, what about giving "clear" URLs?

That's a good idea, I've implemented this in [e12a0dd](https://github.com/nopperl/load-reddit-images-directly/commit/e12a0dd637fa36755591832312e0b8716272ac33).
