### ISSUE TITLE
Commit e12a0dd should be reverted

### ISSUE THREAD

**Issue by Tiagoquix** [nopperl/load-reddit-images-directly#19]
https://github.com/nopperl/load-reddit-images-directly/commit/e12a0dd637fa36755591832312e0b8716272ac33

This commit should be reverted, because in some cases the clear URL doesn't work and requires the other parameters in the URL to work normally. Otherwise, we get `Error 403 Forbidden`.

**Comment by nopperl** [comment]
Yeah, unfortunately, I noticed that too
