### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by MonsterMannen** [nopperl/load-reddit-images-directly#2]
Hello, can you release this as a chrome extension aswell? :)

Think you just need to do some minor manifest changes and its done.

**Comment by nopperl** [comment]
The extension should now be compatible with Chrome. However, I don't have an account for the Chrome Web Store, so I can't publish it there.

**Comment by MonsterMannen** [comment]
Manifest version 2 is deprecated and will soon stop working.

Also the extension doesnt work with chrome (can add it as developer extension without publishing to chrome store)

`The 'webRequest' API cannot be used with event pages.`

**Comment by MonsterMannen** [comment]
Needs to be rewritten to work with manifest version 3

```
{
  "manifest_version": 3,
  "name": "Load Reddit Images Directly",
  "version": "2.0",
  "host_permissions": [
    "https://i.redd.it/*",
    "https://external-preview.redd.it/*",
    "https://preview.redd.it/*"
  ],
  "background": {
    "service_worker": "background.js"
  }
}
```
```
function modifyAcceptHeader(details) {
    console.log("reddit image fix")

    let newHeaders = details.requestHeaders.map(header => {
        if (header.name.toLowerCase() === 'accept') {
            return {
                name: header.name,
                value: 'image/avif,image/webp,*/*'
            };
        }
        return header;
    });
  
    return { requestHeaders: newHeaders };
}
  
self.addEventListener('fetch', event => {
    event.respondWith(
        fetch(event.request, { headers: event.request.headers })
        .then(response => {
            let headers = new Headers(response.headers);
            let modifiedHeaders = modifyAcceptHeader({ requestHeaders: headers });
            return new Response(response.body, {
                status: response.status,
                statusText: response.statusText,
                headers: modifiedHeaders
            });
        })
    );
});
```

Something like this. Not fully working tho :/

**Comment by MonsterMannen** [comment]
I managed to rewrite it for manifest v3 to work in chrome, submitted it and waiting google approval.

https://github.com/MonsterMannen/reddit-load-images-directly-chrome

Mentioned you in the readme :)

**Comment by nopperl** [comment]
Nice, I referred to it in the readme
