### ISSUE TITLE
Posts with multiple images are semi-broken

### ISSUE THREAD

**Issue by Tiagoquix** [nopperl/load-reddit-images-directly#20]
Hi there.

Posts with multiple images do not work well.

Example: https://www.reddit.com/r/pics/comments/1egunhi/olympic_gymnast_giorgia_villa_is_sponsored_by/

The gallery works fine, but clicking one of the images after the first one causes the page to reload instead of opening the clicked image.

**Comment by nopperl** [comment]
Thanks for checking, I didn't try it with galleries, should be fixed now.
