### ISSUE TITLE
extension has to be disabled and re-enabled when browser is relaunched

### ISSUE THREAD

**Issue by treeflowers** [nopperl/load-reddit-images-directly#4]
basically as the title said. i don't know why this happens. but also, reddit might have a new method of redirecting the images than they did when this was last updated

(i'd also think it would be cool if this was made into a violentmonkey script)

**Comment by treeflowers** [comment]
i'd also think it would be cool if this was made into a violentmonkey script

**Comment by SigmaTheDJ** [comment]
I'm experiencing the same issue. I'm using Firefox 119 on Windows 10.

**Comment by SigmaTheDJ** [comment]
@treeflowers I think I have narrowed down the issue in my case. I use an extension called "Don't Accept image/webp", which stops sites from serving up images in WebP format in most cases. That seems to be causing a conflict, because if I disable it, I no longer get the issue with the Reddit images extension.

If you're not using that particular extension, try disabling all extensions except the Reddit images one, then if the issue goes away, re-enable your extensions one at a time until the issue comes back.

**Comment by treeflowers** [comment]
> @treeflowers I think I have narrowed down the issue in my case. I use an extension called "Don't Accept image/webp", which stops sites from serving up images in WebP format in most cases. That seems to be causing a conflict, because if I disable it, I no longer get the issue with the Reddit images extension.
> 
> If you're not using that particular extension, try disabling all extensions except the Reddit images one, then if the issue goes away, re-enable your extensions one at a time until the issue comes back.

i think that worked! i added an exception for reddit in that extension, and now this extension works perfectly! thank you so much

**Comment by SigmaTheDJ** [comment]
> > @treeflowers I think I have narrowed down the issue in my case. I use an extension called "Don't Accept image/webp", which stops sites from serving up images in WebP format in most cases. That seems to be causing a conflict, because if I disable it, I no longer get the issue with the Reddit images extension.
> > If you're not using that particular extension, try disabling all extensions except the Reddit images one, then if the issue goes away, re-enable your extensions one at a time until the issue comes back.
> 
> i think that worked! i added an exception for reddit in that extension, and now this extension works perfectly! thank you so much

No problem! I did the same and have had no issues since.

**Comment by SigmaTheDJ** [comment]
I spoke to the developer of the other extension about this, and he has very kindly updated it so that it will check to see if "Load Reddit images directly" is installed and if it is, it will automatically add the exception for Reddit.

**Comment by nopperl** [comment]
@SigmaTheDJ sorry for the late reply, thanks for investigating a solution for this issue! Since it's fixed by the other extension, I'm closing this issue for now.

**Comment by nopperl** [comment]
@SigmaTheDJ sorry for the late reply, thanks for investigating a solution for this issue! Since it's fixed by the other extension, I'm closing this issue for now.
