### ISSUE TITLE
Feature request: allow direct mouse left-click and middle-click (scroll-click) to open image in current tab and in new tab, respectively

### ISSUE THREAD

**Issue by Tiagoquix** [nopperl/load-reddit-images-directly#9]
Reddit has changed its way of handling image clicks.
Now, when you click on an image, it enlarges a preview on the current tab, and the only way to open the original is by right-clicking and "Open image in new tab".

Example: https://www.reddit.com/r/memes/comments/jnbc9d/i_feel_privileged/

![image](https://github.com/nopperl/load-reddit-images-directly/assets/30274161/cbd2da14-3d88-4c34-b2c5-5a03d4c03185)

![image](https://github.com/nopperl/load-reddit-images-directly/assets/30274161/83891d65-4b18-4108-bd16-726684136500)

**Comment by nopperl** [comment]
Thanks for the suggestion. I have now implemented the clickable behaviour you requested, but it is disabled by default for a few reasons. Most importantly, I have to manipulate the DOM directly to implement this, which will not be robust to future UI updates. Also, it introduces a slight performance overhead. Finally, I'm not convinced that this behaviour is better than the default one (lightbox + direct load on right click only).
